# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(default='Customer Message', max_length=140)),
                ('subDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('read', models.BooleanField(default=True)),
            ],
        ),
    ]
