# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Customer Message', max_length=140),
        ),
        migrations.AlterField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
