# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-01 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161129_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('half', models.TimeField(default=12)),
            ],
        ),
    ]
