# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20161209_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
