# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='content',
            field=models.CharField(default='Content', max_length=5000),
        ),
    ]
