# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('MovieLovers', 'Movie Lovers'), ('FamilyFun', 'Family Fun')], max_length=100)),
                ('comments', models.TextField(max_length=1000)),
                ('time', models.DateField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(default='Bob@bob.com', max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
