# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20170107_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='price',
        ),
    ]
