# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('wage', models.DecimalField(decimal_places=2, default=13.0, max_digits=4)),
            ],
        ),
    ]
