# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=4),
        ),
    ]
