# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-09 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shiftEnd',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shiftStart',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dayWorking',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
