# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20170107_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cms',
        ),
    ]
