# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
