# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
