# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_remove_reserve_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserve',
            name='userid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='package',
            field=models.CharField(choices=[('MovieLovers', 'Movie Lovers'), ('FamilyFun', 'Family Fun')], max_length=100),
        ),
    ]
