# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_auto_20170108_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.AddField(
            model_name='reserve',
            name='email',
            field=models.CharField(default='Bob@bob.com', max_length=100),
        ),
    ]
